### ISSUE TITLE
./main.go:10: undefined: NewRouter

### ISSUE THREAD

**Issue by KITSJonathanDixon** [corylanou/tns-restful-json-api#2]
Hi,

I am having issues when runngin go get on v9 of the project. I get the following error

./main.go:10: undefined: NewRouter

Can anyone explain what is wrong. I have checked my goroot, gobin and gopath variables and they all seem fine.

Thanks

Jonathan

**Comment by gerep** [comment]
Hi @KITSJonathanDixon, maybe you are trying to run the code using `go run main.go`? If so, `go run` is used to run only one file, otherwise you'll have to use `go build` and run the executable generated by it.

One other option is to separate all files into folders and make the proper imports and then you'll be able to run the code with `go run main.go`

**Comment by cdrage** [comment]
@KITSJonathanDixon  @corylanou The original author needs to clarify this for new users.

But in order to run this example. Simple do:

``` bash
go build
```

If you do

``` bash
ls
```

You'll see a binary file. Just run it (it created api for me), so just run:

``` bash
./api
```

and look at localhost:8080
